/** AUTO-GENERATED by scripts/sync_etlap_products.py — do not edit by hand. */

export type EtlapProduct = {
  id: number;
  name: string;
  priceLabel: string;
  /** local path under /public or null if no photo */
  image: string | null;
};

export type EtlapCategory = {
  category: string;
  items: EtlapProduct[];
};

export const ETLAP_SYNCED_FROM =
  "https://www.goletterem.hu/etlap/" as const;

export const ETLAP_CATEGORIES: EtlapCategory[] = 
[
  {
    "category": "Desszertek",
    "items": [
      {
        "id": 200004662,
        "name": "Császármorzsa",
        "priceLabel": "2 190 Ft",
        "image": "/images/etlap/200004662.jpeg"
      },
      {
        "id": 200000161,
        "name": "Lekváros palacsinta",
        "priceLabel": "790 Ft",
        "image": "/images/etlap/200000161.png"
      },
      {
        "id": 200002357,
        "name": "Extra csokis brownie fahéjas meggyraguval",
        "priceLabel": "2 490 Ft",
        "image": null
      },
      {
        "id": 200003801,
        "name": "Somlói kehely",
        "priceLabel": "2 690 Ft",
        "image": null
      },
      {
        "id": 200000165,
        "name": "Mogyorókrémes palacsinta",
        "priceLabel": "990 Ft",
        "image": "/images/etlap/200000165.png"
      },
      {
        "id": 200000164,
        "name": "Túrós palacsinta",
        "priceLabel": "990 Ft",
        "image": "/images/etlap/200000164.png"
      },
      {
        "id": 200000162,
        "name": "Kakaós palacsinta",
        "priceLabel": "790 Ft",
        "image": "/images/etlap/200000162.png"
      },
      {
        "id": 200000338,
        "name": "Gundel palacsinta",
        "priceLabel": "2 690 Ft",
        "image": null
      },
      {
        "id": 200000158,
        "name": "Túrógombóc háziasan édes tejföllel, áfonyával",
        "priceLabel": "2 690 Ft",
        "image": "/images/etlap/200000158.jpg"
      }
    ]
  },
  {
    "category": "Setéshúsból készült ételek",
    "items": [
      {
        "id": 200000332,
        "name": "Velővel töltött karaj/ válassz hozzá köretet",
        "priceLabel": "4 690 Ft",
        "image": "/images/etlap/200000332.jpg"
      },
      {
        "id": 200004660,
        "name": "Sertéspofa juhtúrós sztrapacskával",
        "priceLabel": "6 190 Ft",
        "image": "/images/etlap/200004660.jpeg"
      },
      {
        "id": 200000068,
        "name": "Tonkatsu (japán rántott hús szósz,káposzta,jázmin rizzsel)",
        "priceLabel": "5 990 Ft",
        "image": "/images/etlap/200000068.jpeg"
      },
      {
        "id": 200000064,
        "name": "Ropogós csülök /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000064.jpg"
      },
      {
        "id": 200000067,
        "name": "Cordon bleu szűzből érlelt sonkával, eidami sajttal /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000067.jpg"
      },
      {
        "id": 200000063,
        "name": "Brassói aprópecsenye szűzből",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000063.jpg"
      },
      {
        "id": 200000066,
        "name": "Rókagomba ragu szűzből vörösborosan /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000066.jpg"
      },
      {
        "id": 200000073,
        "name": "Óriás Bécsi szelet szűzből /válassz hozzá köretet/",
        "priceLabel": "4 190 Ft",
        "image": "/images/etlap/200000073.jpg"
      },
      {
        "id": 200000065,
        "name": "Mátrai borzaska/válassz hozzá köretet/",
        "priceLabel": "4 690 Ft",
        "image": "/images/etlap/200000065.jpg"
      },
      {
        "id": 200000062,
        "name": "Tarjasteak szaftosan, pecsenye szaftjával /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000062.jpg"
      },
      {
        "id": 200000071,
        "name": "Rántott karaj /válassz hozzá köretet/",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200000071.jpeg"
      },
      {
        "id": 200000072,
        "name": "Csülök Pékné módra",
        "priceLabel": "5 990 Ft",
        "image": "/images/etlap/200000072.jpg"
      },
      {
        "id": 200000070,
        "name": "Szűzérmék erdei gombamártással /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000070.jpg"
      }
    ]
  },
  {
    "category": "Levesek",
    "items": [
      {
        "id": 200004657,
        "name": "Francia hagymaleves sajtos krutonnal",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200004657.jpeg"
      },
      {
        "id": 200004649,
        "name": "Málnakrémleves túrógombóccal",
        "priceLabel": "2 990 Ft",
        "image": "/images/etlap/200004649.jpeg"
      },
      {
        "id": 200000016,
        "name": "Marhahúsleves tányér",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200000016.jpg"
      },
      {
        "id": 200000007,
        "name": "Marhahúsleves csésze",
        "priceLabel": "2 190 Ft",
        "image": "/images/etlap/200000007.jpg"
      },
      {
        "id": 200000005,
        "name": "Csülkös bableves csésze",
        "priceLabel": "2 190 Ft",
        "image": "/images/etlap/200000005.jpg"
      },
      {
        "id": 200000006,
        "name": "Csülkös bableves tányér",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200000006.jpg"
      },
      {
        "id": 200000004,
        "name": "Jalapenos sajtkrémleves, cheddar chipsszel",
        "priceLabel": "2 990 Ft",
        "image": "/images/etlap/200000004.jpg"
      }
    ]
  },
  {
    "category": "Előételek/Saláták",
    "items": [
      {
        "id": 200004656,
        "name": "Házi lecsó tojással, sült kolbásszal",
        "priceLabel": "3 690 Ft",
        "image": "/images/etlap/200004656.jpeg"
      },
      {
        "id": 200004655,
        "name": "Tojásos galuska szívsalátával",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200004655.jpeg"
      },
      {
        "id": 200000392,
        "name": "Cézársaláta garnélával, pirítóssal",
        "priceLabel": "5 180 Ft",
        "image": "/images/etlap/200000392.jpeg"
      },
      {
        "id": 200000027,
        "name": "Cézársaláta pirított csirkemell csíkokkal, pirítóssal",
        "priceLabel": "4 190 Ft",
        "image": "/images/etlap/200000027.jpg"
      },
      {
        "id": 200000003,
        "name": "Tatár beefsteak zöldségeivel, pirítóssal",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000003.jpg"
      },
      {
        "id": 200000002,
        "name": "Pirított hagymás velő kerti zöldségekkel toasttal",
        "priceLabel": "3 690 Ft",
        "image": "/images/etlap/200000002.jpg"
      },
      {
        "id": 200000329,
        "name": "Rántott Camembert áfonyával, Jázmin rizzsel",
        "priceLabel": "4 690 Ft",
        "image": "/images/etlap/200000329.jpg"
      },
      {
        "id": 200000327,
        "name": "Grill Camembert saláta ágyon, tökmagolajjal",
        "priceLabel": "4 690 Ft",
        "image": "/images/etlap/200000327.jpg"
      },
      {
        "id": 200000028,
        "name": "Görög saláta",
        "priceLabel": "2 190 Ft",
        "image": "/images/etlap/200000028.jpg"
      },
      {
        "id": 200000328,
        "name": "Rántott gomba tartárral",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200000328.jpg"
      },
      {
        "id": 200000029,
        "name": "Rántott sajt tartárral",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200000029.jpg"
      }
    ]
  },
  {
    "category": "Tészták",
    "items": [
      {
        "id": 200000039,
        "name": "Tagliatelle parajos-tejszínes fokhagymás szószban fekete erdei sonkával",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000039.jpg"
      },
      {
        "id": 200000330,
        "name": "Tagliatelle erdei gombás, tejszínes mártással",
        "priceLabel": "4 790 Ft",
        "image": "/images/etlap/200000330.jpg"
      },
      {
        "id": 200004659,
        "name": "Arrabiata ( tagliatelle)",
        "priceLabel": "3 690 Ft",
        "image": null
      },
      {
        "id": 200004658,
        "name": "Juhtúrós sztrapacska",
        "priceLabel": "4 190 Ft",
        "image": null
      },
      {
        "id": 200000038,
        "name": "Tagliatelle bolognai módra reszelt parmezán sajttal",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000038.jpg"
      },
      {
        "id": 200000040,
        "name": "Tagliatelle gremolata parmezán forgáccsal",
        "priceLabel": "3 690 Ft",
        "image": null
      }
    ]
  },
  {
    "category": "Marha, Birka, Szarvas",
    "items": [
      {
        "id": 200000116,
        "name": "Vörösboros marhapörkölt erdei gombával /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000116.jpg"
      },
      {
        "id": 200000270,
        "name": "Sült-párolt marhapofa zöldséges vadas mártásában /válassz hozzá köretet/",
        "priceLabel": "5 990 Ft",
        "image": "/images/etlap/200000270.jpg"
      },
      {
        "id": 200000334,
        "name": "Birkapörkölt/ válassz hozzá köretet",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000334.jpg"
      },
      {
        "id": 200000333,
        "name": "Szarvaspörkölt/ válassz hozzá köretet",
        "priceLabel": "5 190 Ft",
        "image": null
      }
    ]
  },
  {
    "category": "Burgerek",
    "items": [
      {
        "id": 200000131,
        "name": "Barbec burger",
        "priceLabel": "4 790 Ft",
        "image": "/images/etlap/200000131.jpg"
      },
      {
        "id": 200000130,
        "name": "Kézműves hamburger",
        "priceLabel": "4 790 Ft",
        "image": "/images/etlap/200000130.jpg"
      },
      {
        "id": 200000133,
        "name": "Tüzes burger",
        "priceLabel": "4 790 Ft",
        "image": "/images/etlap/200000133.jpeg"
      },
      {
        "id": 200004661,
        "name": "Menüben édesburgonya + coleslaw",
        "priceLabel": "1 990 Ft",
        "image": null
      },
      {
        "id": 200000136,
        "name": "Menüben hasábburgonya + coleslaw",
        "priceLabel": "1 590 Ft",
        "image": null
      },
      {
        "id": 200000335,
        "name": "Menü édesburgonya + coleslaw",
        "priceLabel": "2 190 Ft",
        "image": null
      },
      {
        "id": 200000135,
        "name": "Csibe burger",
        "priceLabel": "3 790 Ft",
        "image": null
      }
    ]
  },
  {
    "category": "Szószok",
    "items": [
      {
        "id": 200002986,
        "name": "Majonéz",
        "priceLabel": "300 Ft",
        "image": null
      },
      {
        "id": 200002985,
        "name": "Hamburgerszósz",
        "priceLabel": "300 Ft",
        "image": null
      },
      {
        "id": 200002982,
        "name": "Tartár mártás",
        "priceLabel": "300 Ft",
        "image": null
      },
      {
        "id": 200002983,
        "name": "Zöldfűszeres majonéz",
        "priceLabel": "300 Ft",
        "image": null
      },
      {
        "id": 200002984,
        "name": "Ketchup",
        "priceLabel": "300 Ft",
        "image": null
      }
    ]
  },
  {
    "category": "Steak ajánlat",
    "items": [
      {
        "id": 200000120,
        "name": "Hátszínsteak fűszervajjal, sült paprikával, édesburgonyával",
        "priceLabel": "9 990 Ft",
        "image": "/images/etlap/200000120.png"
      },
      {
        "id": 200000119,
        "name": "Bészínsteak gorgonzola mártással paremzános burgonyapürével",
        "priceLabel": "11 990 Ft",
        "image": null
      },
      {
        "id": 200000118,
        "name": "Bélszínsteak zöldborsmártással, sült paprikával, steak burgonyával",
        "priceLabel": "11 990 Ft",
        "image": "/images/etlap/200000118.jpeg"
      },
      {
        "id": 200000121,
        "name": "Hátszínsteak erdei gombamártással, krokettal",
        "priceLabel": "9 990 Ft",
        "image": "/images/etlap/200000121.png"
      }
    ]
  },
  {
    "category": "Szárnyasból készült ételek",
    "items": [
      {
        "id": 200000052,
        "name": "Kacsamell rosé-ra sütve /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000052.jpg"
      },
      {
        "id": 200000056,
        "name": "Pirított kacsamell érmék kéksajt mártással /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000056.jpg"
      },
      {
        "id": 200000053,
        "name": "Ropogós kacsacomb /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000053.jpg"
      },
      {
        "id": 200000059,
        "name": "Shaun Hill serpenyős csirkéje pankó morzsában (zöldfűszer, mustár) /válassz hozzá köretet/",
        "priceLabel": "4 190 Ft",
        "image": "/images/etlap/200000059.jpeg"
      },
      {
        "id": 200000055,
        "name": "Egészben sült csirkemell jalapenos cheddar mártással /válassz hozzá köretet/",
        "priceLabel": "4 190 Ft",
        "image": "/images/etlap/200000055.jpeg"
      },
      {
        "id": 200000050,
        "name": "Mediterrán csirkemell fűszeres mártásban /válassz hozzá köretet/",
        "priceLabel": "4 790 Ft",
        "image": "/images/etlap/200000050.jpg"
      },
      {
        "id": 200000057,
        "name": "Parmezán bundában sült csirkemell /válassz hozzá köretet/",
        "priceLabel": "4 190 Ft",
        "image": null
      },
      {
        "id": 200000054,
        "name": "Kijevi jércemell zöldfűszeres vajjal töltve /válassz hozzá köretet/",
        "priceLabel": "4 190 Ft",
        "image": "/images/etlap/200000054.jpg"
      },
      {
        "id": 200000051,
        "name": "Mézes-mustáros csirkemell filé /válassz hozzá köretet/",
        "priceLabel": "4 190 Ft",
        "image": "/images/etlap/200000051.jpg"
      },
      {
        "id": 200000048,
        "name": "Rántott csirkecomb filé /válassz hozzá köretet/",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200000048.jpg"
      },
      {
        "id": 200000058,
        "name": "Rántott csirkemell /válassz hozzá köretet/",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200000058.jpg"
      },
      {
        "id": 200000060,
        "name": "Vasalt csirkecombfilé /válassz hozzá köretet/",
        "priceLabel": "3 190 Ft",
        "image": "/images/etlap/200000060.jpg"
      }
    ]
  },
  {
    "category": "Halak",
    "items": [
      {
        "id": 200000331,
        "name": "Fogasfilé rántva, zöld-fűszeres majonézzel/ válassz hozzá köretet/",
        "priceLabel": "4 690 Ft",
        "image": "/images/etlap/200000331.png"
      },
      {
        "id": 200002743,
        "name": "Fish and chips atlanti tőkehalból, zöldfűszeres majonézzel édesburgonyával",
        "priceLabel": "7 190 Ft",
        "image": "/images/etlap/200002743.jpeg"
      },
      {
        "id": 200000045,
        "name": "Pisztráng olíván sütve fokhagymával,mandulával /válassz hozzá köretet/",
        "priceLabel": "5 190 Ft",
        "image": "/images/etlap/200000045.jpg"
      },
      {
        "id": 200000044,
        "name": "Fogasfilé bőrén sütve parajágyon /válassz hozzá köretet/",
        "priceLabel": "4 690 Ft",
        "image": "/images/etlap/200000044.jpg"
      },
      {
        "id": 200000043,
        "name": "Lazac steak vajon, olíván sütve /válassz hozzá köretet/",
        "priceLabel": "4 690 Ft",
        "image": "/images/etlap/200000043.jpg"
      },
      {
        "id": 200000047,
        "name": "Hekk /válassz hozzá köretet/",
        "priceLabel": "4 190 Ft",
        "image": "/images/etlap/200000047.jpg"
      },
      {
        "id": 200000046,
        "name": "Fish and chips atlanti tőkehalból, zöldfűszeres majonézzel",
        "priceLabel": "6 190 Ft",
        "image": "/images/etlap/200000046.jpg"
      }
    ]
  },
  {
    "category": "Köretek",
    "items": [
      {
        "id": 200000318,
        "name": "Édesburgonya",
        "priceLabel": "1 990 Ft",
        "image": null
      },
      {
        "id": 200000217,
        "name": "Friss-kevert saláta",
        "priceLabel": "1 790 Ft",
        "image": "/images/etlap/200000217.jpg"
      },
      {
        "id": 200000214,
        "name": "Burgonyapüré",
        "priceLabel": "1 390 Ft",
        "image": "/images/etlap/200000214.png"
      },
      {
        "id": 200000219,
        "name": "Petrezselymes burgonya",
        "priceLabel": "1 290 Ft",
        "image": null
      },
      {
        "id": 200000216,
        "name": "Hagymás törtburgonya",
        "priceLabel": "1 290 Ft",
        "image": null
      },
      {
        "id": 200000223,
        "name": "Krokett",
        "priceLabel": "1 290 Ft",
        "image": null
      },
      {
        "id": 200003676,
        "name": "Zsemlegombóc",
        "priceLabel": "1 390 Ft",
        "image": null
      },
      {
        "id": 200000213,
        "name": "Steakburgonya",
        "priceLabel": "1 290 Ft",
        "image": null
      },
      {
        "id": 200000215,
        "name": "Thai Jázmin rizs",
        "priceLabel": "1 090 Ft",
        "image": null
      },
      {
        "id": 200000222,
        "name": "Rizi-bizi",
        "priceLabel": "1 290 Ft",
        "image": null
      },
      {
        "id": 200000211,
        "name": "Hasábburgonya",
        "priceLabel": "1 290 Ft",
        "image": "/images/etlap/200000211.jpg"
      },
      {
        "id": 200000210,
        "name": "Parasztos burgonya hagymával-szalonnával",
        "priceLabel": "1 490 Ft",
        "image": null
      },
      {
        "id": 200000225,
        "name": "Párolt lilakáposzta",
        "priceLabel": "1 290 Ft",
        "image": "/images/etlap/200000225.png"
      },
      {
        "id": 200000224,
        "name": "Párolt zöldség",
        "priceLabel": "1 490 Ft",
        "image": null
      },
      {
        "id": 200000226,
        "name": "Galuska",
        "priceLabel": "1 090 Ft",
        "image": null
      },
      {
        "id": 200000220,
        "name": "Coleslaw saláta (amerikai majonézes káposztasaláta)",
        "priceLabel": "1 490 Ft",
        "image": null
      }
    ]
  },
  {
    "category": "Savanyúságok",
    "items": [
      {
        "id": 200000230,
        "name": "Csemege uborka",
        "priceLabel": "990 Ft",
        "image": "/images/etlap/200000230.png"
      },
      {
        "id": 200000231,
        "name": "Csípős káposzta",
        "priceLabel": "990 Ft",
        "image": null
      },
      {
        "id": 200000336,
        "name": "Uborka saláta tejföl nélkül",
        "priceLabel": "990 Ft",
        "image": "/images/etlap/200000336.png"
      },
      {
        "id": 200000232,
        "name": "Házi káposztasaláta",
        "priceLabel": "990 Ft",
        "image": "/images/etlap/200000232.png"
      },
      {
        "id": 200000233,
        "name": "Tejfölös uborkasaláta",
        "priceLabel": "990 Ft",
        "image": null
      },
      {
        "id": 200000235,
        "name": "Zöldsaláta olívával, balzsamecettel",
        "priceLabel": "1 390 Ft",
        "image": null
      },
      {
        "id": 200000234,
        "name": "Cékla (idény jelleggel)",
        "priceLabel": "990 Ft",
        "image": null
      },
      {
        "id": 200000227,
        "name": "Ecetes cseresznyepaprika",
        "priceLabel": "990 Ft",
        "image": null
      },
      {
        "id": 200000228,
        "name": "Ecetes almapaprika",
        "priceLabel": "990 Ft",
        "image": "/images/etlap/200000228.png"
      }
    ]
  },
  {
    "category": "Heti menü",
    "items": [
      {
        "id": 200000190,
        "name": "Menü A (csomagolási díjat tartalmaz)",
        "priceLabel": "3 590 Ft",
        "image": null
      },
      {
        "id": 200000188,
        "name": "Menü B (csomagolási díjat tartalmaz)",
        "priceLabel": "3 590 Ft",
        "image": null
      }
    ]
  },
  {
    "category": "Gól tálak",
    "items": [
      {
        "id": 200000185,
        "name": "Csülkös tál",
        "priceLabel": "16 590 Ft",
        "image": "/images/etlap/200000185.jpg"
      },
      {
        "id": 200000306,
        "name": "Gól tál",
        "priceLabel": "20 590 Ft",
        "image": "/images/etlap/200000306.jpg"
      },
      {
        "id": 200000308,
        "name": "Vega tál",
        "priceLabel": "19 590 Ft",
        "image": "/images/etlap/200000308.jpg"
      }
    ]
  }
];
